github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_TOKEN}

spring:
  main:
    banner-mode: off
  datasource:
    username: root
    password: ${PASSWORD}
    url: jdbc:mysql://localhost:3306/gamification_app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
  file:
    name: logs/app.log

server:
  port: 8080